before_install:
  - sudo apt-get update
  - sudo apt-get install -y mmdb-bin
language: node_js
node_js:
  - stable
git:
  depth: 1
branches:
  only:
    - master
after_success:
  - "npm run coveralls"
